# SPDX-License-Identifier: GPL-2.0-only
# Create the activation journal directory. Age deletion is not used: the
# Python pruner removes only proved-terminal histories.
d /var/lib/t2-touchid/activation 0700 root root -
