# SPDX-License-Identifier: GPL-2.0-only
# Requires Linux >= 6.12 (linux/hex.h, linux/unaligned.h, pcim_iomap_region).
PACKAGE_NAME="t2-sep-transport"
PACKAGE_VERSION="0.1.0"
BUILT_MODULE_NAME[0]="t2_sep_transport"
BUILT_MODULE_LOCATION[0]="src"
DEST_MODULE_LOCATION[0]="/kernel/drivers/misc"
MAKE[0]="make -C src KDIR=/lib/modules/$kernelver/build module"
AUTOINSTALL="yes"
BUILD_EXCLUSIVE_KERNEL="^(6\.(1[2-9]|[2-9][0-9])|[7-9]\.)"
