PACKAGE_NAME="applesmc-t2touch"
PACKAGE_VERSION="0.1.0"
AUTOINSTALL="yes"

MAKE[0]="make KERNELRELEASE=${kernelver} KDIR=/lib/modules/${kernelver}/build"
CLEAN="make KERNELRELEASE=${kernelver} KDIR=/lib/modules/${kernelver}/build clean"

BUILT_MODULE_NAME[0]="applesmc"
DEST_MODULE_LOCATION[0]="/updates/dkms"
